using Egyptos.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Reflection.Emit;

namespace Egyptos.Infrastructure.Data.Configurations;

public class HistoricalConfiguration : IEntityTypeConfiguration<Historical>
{
    public void Configure(EntityTypeBuilder<Historical> builder)
    {
        var historucal = new List<Historical>
        {
            new Historical
            {
                Id = 1,
                Title = "Ayyubid State",
                Date = "1171 AD / 1250 AD",
                Description = "The Ayyubid state was founded by Saladin, who defeated the Fatimids and expelled them from Egypt in 567 AH / 1174 AD, and Egypt returned under the rule of the Abbasid Caliphate again.\r\n\r\nSaladin worked to spread the Sunni doctrine instead of the Shiite doctrine that was prevalent in the Fatimid era.\r\n\r\nThe Ayyubid state was a military state as it appeared during the Crusades in Egypt and the Levant.\r\n\r\nIn light of this political context, Saladin decided to build a castle in Cairo, which began construction in 527 AH / 1176 AD, but its completion was not completed during his lifetime, but later in 1208 AD. Therefore, the rule of Egypt extended to the Levant, the Hijaz, Yemen, Nubia and parts of North Africa. The Ayyubid era in Egypt lasted for 81 years and ended at the hands of the Mamluks.",
                ImageUrl = "HistoricalImages/1.jpg",
            },
            new Historical
            {
                Id = 2,
                Title = "Modern State",
                Date = "1550 BC / 1069 BC",
                Description = "During the New Kingdom, Egypt became a great empire that stretched across the ancient Near East, reaching as far south as the Fourth Cataract in Nubia, and as far north as the Levant. The Egyptian economy flourished to an astonishing degree, and most of the most famous and impressive ancient Egyptian monuments date back to this great period.\r\n\r\nThe Eighteenth Dynasty (1550-1295 BC) began with King Ahmose, who expelled the Hyksos, a Semitic people who ruled most of Egypt during the Second Intermediate Period. Most of the kings of the New Kingdom pursued an expansionist foreign policy in response to what had happened before, and the wealth generated by the expansions was used to carry out many construction projects throughout Egypt, especially at the Karnak Temple in Luxor, the most important temple of Amun, the lord of Thebes. Most of the kings of this dynasty were buried in the famous Valley of the Kings.\r\n\r\nArt, architecture, and the national economy reached new heights under Hatshepsut. Unfortunately, her husband, Thutmose II, did not rule for long, while his son from another wife, Thutmose III, was still too young to rule. So the Great Royal Wife Hatshepsut, perhaps in order to secure the throne of Egypt, declared herself king alongside her young stepson. Hatshepsut developed a new concept of kingship and linked herself to a divine birth from the god Amun to legitimize her reign, leaving a profound mark on the geographic, religious, and political landscape of Thebes.\r\n\r\nThutmose III proved to be the most capable king of all. During his reign, Egypt’s borders were extended farther, and his influence extended throughout the Nile Valley, including Nubia, leaving many monuments at the Karnak Temple, as Hatshepsut had done before. Peace was achieved in the region during the reign of his son Amenhotep II, and both the state of peace and increased international trade bore fruit under his successor Amenhotep III. Few kings matched him in the quality, scale, and quantity of his building projects, as he built many structures throughout Egypt and Nubia, including half of the Luxor Temple as it stands today.\r\n\r\nHowever, Amenhotep IV, son of Amenhotep III, changed his name to Akhenaten and declared his rebellion against the rest of the gods and that there is only one god, Aten, who was represented as the sun disk in the sky. His reign witnessed other revolutionary changes in royal ideology, art, architecture and language. However, he neglected Egypt's foreign affairs, and by the end of his reign, Egypt's lands in the Levant (the area of ​​Palestine, Lebanon and Syria) were lost.\r\n\r\nA turbulent period followed his reign, with Horemheb - a former army commander - ascending to the throne and completing the return of things to normal, appointing the commander Bar-Amesu as his successor. With his ascension to the throne under the name Ramesses I, the Nineteenth Dynasty (c. 1295-1186 BC) began, and his son Seti I succeeded him and ushered in an era of prosperity in Egypt. He also carried out many military campaigns, the most important of which were against the Hittites, who emerged as a new power in the ancient Near East, and regained much of Egypt's lost lands in the Levant.\r\n\r\nHis son Ramses II the Great was one of the most successful kings in ancient Egyptian history. During his long reign he waged many successful wars, achieved the first peace treaty with the Hittites, and left more monuments throughout Egypt than any other king. Meanwhile, his successor and son Merneptah launched a major attack against tribes called the \"Sea Peoples\", and by the end of his reign the Nineteenth Dynasty declined.\r\n\r\nWith the reign of King Setnakht, founder of the Twentieth Dynasty (1896-1069 BC), order returned to the country, and his son Ramses III was the last great warrior of the New Kingdom. After him, the state deteriorated steadily until it was divided into two parts. The next dynasty ruled only Lower Egypt, while Upper Egypt remained under the rule of the priests.\r\nThe New Kingdom",
                ImageUrl = "HistoricalImages/8.jpeg",
            },
            new Historical
            {
                Id = 3,
                Title = "Tulunid State",
                Date = "868 AD / 905 AD",
                Description = "The Tulunids established the first independent state in Egypt during the Abbasid era, during which Egypt was able to retain all its wealth. Ahmed Ibn Tulun, the founder of the Tulunid state, carried out many economic and cultural reforms, where he began by establishing a new administrative capital called Al-Qata'i, and built his mos\r\nque, currently known as the Ibn Tulun Mosque. The rule of the Tulunids lasted for about thirty-five years, after which came the Ikhshidids.",
                ImageUrl = "HistoricalImages/12.jpg",
            },
            new Historical
            {
                Id = 4,
                Title = "Fatimid State",
                Date = "912 AD / 1171 AD",
                Description = "The Fatimid state was the golden age of Egypt, in which Islamic art was completed, as Egyptian artists left behind many monuments and artifacts that testify to their superior skill and precision in various artistic forms.\r\nThe Fatimids invaded Egypt in 358 AH / 969 AD, then established a new city north of Fustat, which they called \"Cairo\", making it their capital. Al-Azhar Mosque was the first mosque they built in Cairo.",
                ImageUrl = "HistoricalImages/16.jpg",
            },
            new Historical
            {
                Id = 5,
                Title = "Old Kingdom",
                Date = "2686 BC / 2181 BC",
                Description = "The Old Kingdom extends through the third to sixth dynasties, as the king's power increased during that period. King Djoser, the first king of the Third Dynasty, built his step pyramid in Saqqara. He wanted to build a mastaba-shaped tomb in the style of his predecessors, the kings of the First and Second Dynasties, but those mastabas increased to reach about five mastabas, one above the other.To be the first stone step pyramid in the country's history. But his successors were unable to complete their pyramids, perhaps due to the short duration of their rule.\r\nWe do not know much about King Huni, the first king of the Fourth Dynasty, while the second king, Senefru (2613-2589 BC), was very powerful and advanced. He alone built three pyramids, the first of which was in the city of Meidum, which began as a step pyramid and then ended as a complete pyramid. . As for the second, he built it in Dahshur and is known as the Bent Pyramid or the Broken Pyramid. It was the first attempt to build a pyramid.Complete, but its construction was not completed as he wanted, while the third pyramid, known as the Red Pyramid in Dahshur, was the first complete pyramid in Egypt, which opened the way for the construction of complete pyramids. This was achieved during the reign of his successor, King Khufu (c. 2589 - 2566 BC), who built the largest pyramid and pyramid group. The Great Pyramid, with an original height of 146.5 metres, was the tallest building in the world for 3,800 years. Khufu's son and successor, Ra (about 2566 - 2558 BC), did not complete his pyramid at Abu Rawash.\r\nHe was succeeded by Khafre (ca. 2555 - 2532 BC), during whose reign he carved the Great Sphinx and built a pyramid nearly the size of his father's pyramid. As for the two temples connected to the pyramid, they were larger and more detailed than the temples of its predecessors.\r\nThe pyramid of Menkaure (2532 - 2503 BC), son of King Khafre, is considered an example of the beginning of the decline of royal authority. Although his pyramid was considerably smaller than its predecessors, at least a quarter of it was covered in granite, a stone brought from Aswan that was difficult to obtain and transport. Moreover, the temples adjacent to his temple are relatively larger than their predecessors, indicating a shift in the king's priorities from his tomb to the worship to be practiced in these temples.\r\nThis trend grew more pronounced during the Fifth Dynasty (ca. 2449 - 2487 BC) and the Sixth Dynasty (ca. 2345 - 1821 BC). The last king of the Fifth Dynasty, Unas, ordered the creation of inscriptions inside his pyramid at Saqqara, known as the Pyramid Texts, an introduction to a famous series of texts known as the Book of the Dead. The purpose of these texts was to help the king successfully reach the afterlife and become a deity.\r\nBeginning in the Sixth Dynasty it became clear that the king's authority had declined. In addition to other factors, by the end of the long reign of its last king, Pipi II (c. 278-2184 BC), Egypt was no longer under the control of a central government.",
                ImageUrl = "HistoricalImages/22.webp",
            },
            new Historical
            {
                Id = 6,
                Title = "Middle Kingdom",
                Date = "2055 BC / 1650 BC",
                Description = "The Middle Kingdom was a period of great prosperity, consisting of the Eleventh to Thirteenth Dynasties. Although the Eleventh Dynasty had its origins in the First Intermediate Period, the last king of this era who succeeded in unifying Egypt, thus beginning the Middle Kingdom, was King Nebhepetre Mentuhotep (ca. 2055 - 2004 BC). The Eleventh Dynasty came from Thebes (now Luxor). It was not an important city during that period, but it will become one of the most prominent and important cities in Egypt during the rest of ancient Egyptian history\r\nBecause of his Theban origins, Nebhepetre-Mentuhotep was buried on the western mainland of Thebes in the Deir el-Bahri area. His tomb included a temple for his funeral rituals. The tomb was partly cut into a rocky slope, while part of it was built in the form of a terrace that included an ascending middle slope. This temple was clearly a partial inspiration for the neighboring and more famous temple of Queen Hatshepsut to its immediate left.\r\nLittle is known about Mentuhotep III and IV, the last rulers of the Eleventh Dynasty. Amenemhat I (1985-1955 BC) was the first king of the Twelfth Dynasty (1985-1795 BC) and was probably the vizier of Mentuhotep IV. The kings of this highly successful dynasty consolidated the authority of the central government over all of Egypt, and during this period the powerful provincial rulers were reined in.They also undertook building projects throughout the country, strengthened its borders, sent mining expeditions, and encouraged trade voyages. A series of forts, such as those at Bohn, Semna and Ascot, not only served as defensive fortresses but regulated the movement of incoming Nubian traders and were bases for mining and military operations. The reign of Kings Senusret III (1874-1855 BC) and Amenemhat III (1850-1808 BC) was particularly prosperous.\r\nHuge agricultural projects were implemented during that period, especially in the Fayoum region in Central Egypt, where canals were dug, part of the lake was dredged, and the resulting lands were reclaimed for agriculture. The kings of the Twelfth Dynasty in this region were buried in huge pyramids near the new capital founded by Amenemhat I, which was called Etet Tawi, meaning the Holder of the Two Lands, and its exact location is still unknown.\r\nThe Middle Kingdom represented an important shift in the history of ancient Egyptian culture, as its most important contributions to ancient Egyptian language and literature were: new linguistic structures emerged and many new literary texts were written, many of which remain popular for more than a millennium. The language used to write these texts, with its grammatical rules, is called the Middle Egyptian language, which will serve as the language of official texts until the Ptolemaic era (332-30 BC) and the Roman era (30 BC - 395 AD).",
                ImageUrl = "HistoricalImages/26.jpg",
            },
            new Historical
            {
                Id = 7,
                Title = "Umayyad era",
                Date = "661 AD / 750 AD",
                Description = "The Umayyad Caliphate was founded by Muawiyah ibn Abi Sufyan, and the Umayyad rule lasted for nearly a century.\r\nThe borders of the Umayyad state extended to Europe and the edges of Asia, however, the caliphate collapsed during the reign of Caliph Hisham ibn Abd al-Malik.\r\nDamascus was the center of government, and Egypt was one of its states. Amr ibn al-Aas was appointed governor of Egypt for the second time by Caliph Muawiyah ibn Abi Sufyan (38-43 AH), and he is considered the first ruler of Egypt during this period.",
                ImageUrl = "HistoricalImages/31.jpg",
            },
            new Historical
            {
                Id = 8,
                Title = "Ptolemaic era",
                Date = "332 BC / 30 BC",
                Description = "Egypt became part of the Macedonian Empire after Alexander the Great defeated the Persian king Darius III in 332 BC. After Alexander's death in 323 BC and the division of his estate among his generals, Egypt came under the rule of Ptolemy I (Soter), who made Egypt an independent kingdom known as the Ptolemaic state.\r\nPtolemy I completed the construction of the new capital of Egypt - Alexandria, and began building the Lighthouse of Alexandria and gathered both Egyptian and Greek priests in order to establish a new faith that would unite Egyptians and Greeks together. During the reign of his successor, Ptolemy II, the arts and sciences flourished and the ancient Library of Alexandria was established, which was the largest library in the ancient world, which led to the influx of Greek scholars and thinkers to Egypt and increased cultural diversity and merged the new Greek civilization with the ancient Egyptian civilization.\r\nVarious Greek settlements were established in Egypt during the Ptolemaic period as major central areas for Greek citizens who came to Egypt with their culture and traditions, such as \"Ptolemae\" in Upper Egypt, \"Philadelphia\" in Fayoum, and \"Naukratis\", which was the first Greek settlement and a center of trade between Egyptians and Greeks in the Delta, which was established during the Late Period. In the ancient capital of Memphis, Greek settlers established their settlement around the main temple of Ptah in the early Ptolemaic period. The rule of the Ptolemies in Egypt came to a tragic end when they were defeated by the Romans at the Battle of Actium in 31 BC, which led to the suicide of Queen Cleopatra VII and the killing of her son, Ptolemy XV Caesarion.",
                ImageUrl = "HistoricalImages/36.jpg",
            },
            new Historical
            {
                Id = 9,
                Title = "Roman era",
                Date = "30 BC / 395 AD",
                Description = "After the naval battle of Actium and the defeat of Antony and Queen Cleopatra VII in 31 BC by the commander Octavian (Augustus), Egypt lost its independence and became a province of the new empire ruled by the Roman emperor, who was installed as pharaoh and the country was divided into three regions, each ruled by a local governor, but all of them were under the authority of the emperor.\r\nThings Egypt exploited Egypt Abad, and some emperors were interested in Egypt in particular, such as the Roman emperor Hadrian who visited Egypt and established the new Roman tariff called \"Antineopolis\", and the Romans talked about new agricultural techniques where they built new water chambers and dams, in addition to increasing grain production and expanding the cultivation of wine. All of these agricultural divisions include their primary goal to be the \"breadbasket of the ancient world\" and nothing more.\r\nLife in Egypt was influenced by a multi-festival culture during the Roman Empire and was involved in artistic influences from Greek and Roman culture, leading to the emergence of a unique artistic style and demonstrating the Egyptian intellectual influence in the spread of the worship of Isis throughout the Roman Empire.\r\nIn 285 AD the Roman Empire was divided into an Eastern and Western Empire, and the new state ended with the fall of Rome to the attacks of the Berbers, while the Eastern Empire took control and became known as the Byzantine Empire in 330 AD.",
                ImageUrl = "HistoricalImages/41.jpg",
            },
            new Historical
            {
                Id = 10,
                Title = "Abbasid era",
                Date = "750 AD / 1517 AD",
                Description = "Abdullah al-Saffah ibn Muhammad (Abu al-Abbas al-Saffah) is the founder of the Abbasid state. He came to power after the Abbasids defeated the Umayyads in 132 AH / 750 AD. Their rule of the country extended to eight centuries, and the Abbasids were the ones who represented the political legitimacy of Muslims at that time. The Abbasid Empire was one of the largest empires, and Kufa in Iraq was the capital at first, then Caliph Abu Jaafar al-Mansur founded the city of Baghdad and moved the capital to it.",
                ImageUrl = "HistoricalImages/46.jpg",
            },
            new Historical
            {
                Id = 11,
                Title = "Circassian Mamluk State (Burji)",
                Date = "1382 AD / 1517 AD",
                Description = "The Circassian Mamluks founded their state in 784 AH/1382 AD through Sayf al-Din Barquq. Their roots go back to the reign of al-Mansur Qalawun, who used them extensively in his army. This group was loyal to him when he became a military general. One of these Circassian Mamluks, Barquq, became the most important and powerful man in the state. His ascension to the throne marked the beginning of the Circassian Mamluk dynasty. They were also called Burji (derived from \"tower\") Mamluks, as they occupied the citadel and its towers. Egypt witnessed architectural and artistic progress during the Mamluk era, although it was an unstable period. The Circassian Mamluks ruled Egypt for about 135 years under 23 alternating sultans. The defeat of Sultan Tuman Bay marked the beginning of the Ottoman era.",
                ImageUrl = "HistoricalImages/51.webp",
            },
            new Historical
            {
                Id = 12,
                Title = "Ottoman era",
                Date = "1517 AD / 1805 AD",
                Description = "Ottoman rule in Egypt began with the victory of Sultan Selim I over the Mamluk Sultan Tuman Bay in the Battle of Ridaniya in 1517 AD. Egypt became a province subject to the Ottomans, and the capital of the Ottoman Empire was in Constantinople. Ottoman rule in Egypt continued until the beginning of the French campaign in Egypt in (1798-1801 AD), then Ottoman rule returned again until 1805 AD. No important political developments occurred in Egypt during this period, other than the ongoing competition between the Ottoman and Mamluk rulers.",
                ImageUrl = "HistoricalImages/56.webp",
            },
            new Historical
            {
                Id = 13,
                Title = "The era of the Muhammad Ali dynasty",
                Date = "1805 AD / 1953 AD",
                Description = "This period was founded by Muhammad Ali Pasha, and his family's rule lasted for more than one hundred and fifty years. Science, art, and culture developed and flourished during this period, and Egypt became one of the greatest kingdoms of the East, as Muhammad Ali planned for the modernization of the country. His plan included new educational, agricultural, and industrial systems, and the establishment of a strong military base. As for architectural development, it began during the reign of Khedive Ismail, who wanted to make Cairo the Paris of the East, as he worked to a large extent on developing the construction features, so he deserves the title of \"the second founder of modern Egypt\" after Muhammad Ali. During his reign, the seat of government was moved from the Citadel to Abdeen Palace. Khedive Abbas Hilmi II continued to establish the modern state, where the Egyptian University (currently known as Cairo University) was built. Then Egypt became a kingdom during the reign of King Fuad I, who founded many scientific institutions. He was succeeded by King Farouk. Until the 1952 revolution, the rule of the royal family in Egypt ended in 1953.",
                ImageUrl = "HistoricalImages/63.jpg",
            },
            new Historical
            {
                Id = 14,
                Title = "The era of the Rightly Guided Caliphs",
                Date = "632 AD / 661 AD ",
                Description = "This era was named after the four Rightly Guided Caliphs who succeeded the Prophet Muhammad, may God bless him and grant him peace, in ruling the Islamic state. This era is considered one of the greatest eras in Islamic history. The fierce wars between the Persians and the Romans had exhausted their forces, which contributed to the expansion of the Islamic state at their expense. In 20 AH/641 AD, Caliph Omar bin Al-Khattab (13-23 AH/634-644 AD) conquered Egypt and freed it from the Byzantine occupation, which in turn had occupied it after expelling the Sassanid Persians. Egypt was conquered by the commander Amr bin Al-Aas, who made Alexandria his capital. However, Caliph Omar bin Al-Khattab refused the order because he wanted the capital of Egypt to be close to Medina, the capital of the Caliphate. Therefore, Ibn Al-Aas, as governor of Egypt, built a new capital for the country, the city of Fustat, on whose ruins the city of Cairo was built 300 years later to remain the capital of Egypt.",
                ImageUrl = "HistoricalImages/69.jpg",
            },
            new Historical
            {
                Id = 15,
                Title = "Pre-dynastic era",
                Date = "5500 BC / 3100 BC",
                Description = "This name covers the period of ancient Egyptian prehistory, beginning with the Old Stone Age (Paleolithic), and ending with the end of the New Stone Age (Neolithic). The term \"prehistory\" refers to the pre-writing stage in Egypt. Writing appeared at about the same time as the end of the Stone Age, around 3100 BC. This is the period in which Egypt emerged as a unified political entity, making it the oldest country in the world\r\nBefore the formation of the Egyptian state and during the Neolithic, an increasing homogeneity can be seen between the different civilizations that emerged along the Nile Valley, with those civilizations being named after their original sites. Among the most important of them is the Maadi civilization (4000 - 3100 BC) in Lower Egypt. The Badari civilization (ca. 500-4000 BC) near Asyut and Naqada I (ca. 4000-3500 BC) in Upper Egypt near Luxor.\r\nLike the rest of its contemporaries, Naqada I reveals little about social stratification, but this changed by the end of this period. This trend became more evident during Naqada II (ca. 3500 - 3200 BC), which began to spread along the Nile Valley. Among the most important Naqada II sites, besides Naqada itself, were Hierakonpolis (Kom el-Ahmar) near Edfu, and Abydos in Upper Egypt. During the Naqada III civilization (ca. 3500 - 3100 BC),The community continued to grow more complex and diverged from and politically separated itself from contemporary Nubian culture. The transition from the Naqada III civilization to the early dynastic period was smooth, which is why Naqada III is sometimes called the “Zero Dynasty.”\r\nIt appears that the powerful regional leaders during this period already controlled most, if not all, of the land of Egypt. There was a difference between Upper and Lower Egypt geographically. This difference remained apparent until the late prehistoric era, and the ancient Egyptians did not forget this matter throughout their ancient history despite the unity. When Egypt eventually became unified as a single political entity under one ruler, the ancient Egyptians referred to their king as “Lord of the Two Lands.",
                ImageUrl = "HistoricalImages/71.jpg",
            },
        };

        builder.HasData(historucal);
    }
}

public class HistoricalImagesConfiguration : IEntityTypeConfiguration<HistoricalImage>
{
    public void Configure(EntityTypeBuilder<HistoricalImage> builder)
    {
        var historicalImage = new List<HistoricalImage>
        {
            new HistoricalImage
            {
                Id = 1,
                ImageUrl = "HistoricalImages/2.jpg",
                HistoricalId = 1
            },
            new HistoricalImage
            {
                Id = 2,
                ImageUrl = "HistoricalImages/3.jpg",
                HistoricalId = 1
            },
            new HistoricalImage
            {
                Id = 3,
                ImageUrl = "HistoricalImages/4.jpg",
                HistoricalId = 1
            },
            new HistoricalImage
            {
                Id = 4,
                ImageUrl = "HistoricalImages/5.jpg",
                HistoricalId = 1
            },
            new HistoricalImage
            {
                Id = 5,
                ImageUrl = "HistoricalImages/6.jpeg",
                HistoricalId = 2
            },
            new HistoricalImage
            {
                Id = 6,
                ImageUrl = "HistoricalImages/7.jpeg",
                HistoricalId = 2
            },
            new HistoricalImage
            {
                Id = 7,
                ImageUrl = "HistoricalImages/9.jpeg",
                HistoricalId = 2
            },
            new HistoricalImage
            {
                Id = 8,
                ImageUrl = "HistoricalImages/10.jpeg",
                HistoricalId = 2
            },
            new HistoricalImage
            {
                Id = 9,
                ImageUrl = "HistoricalImages/11.jpg",
                HistoricalId = 3
            },
            new HistoricalImage
            {
                Id = 10,
                ImageUrl = "HistoricalImages/13.jpg",
                HistoricalId = 3
            },
            new HistoricalImage
            {
                Id = 11,
                ImageUrl = "HistoricalImages/14.jpg",
                HistoricalId = 3
            },
            new HistoricalImage
            {
                Id = 12,
                ImageUrl = "HistoricalImages/15.jpg",
                HistoricalId = 3
            },
            new HistoricalImage
            {
                Id = 13,
                ImageUrl = "HistoricalImages/17.jpg",
                HistoricalId = 4
            },
            new HistoricalImage
            {
                Id = 14,
                ImageUrl = "HistoricalImages/18.jpg",
                HistoricalId = 4
            },
            new HistoricalImage
            {
                Id = 15,
                ImageUrl = "HistoricalImages/19.jpg",
                HistoricalId = 4
            },
            new HistoricalImage
            {
                Id = 16,
                ImageUrl = "HistoricalImages/20.jpg",
                HistoricalId = 4
            },
            new HistoricalImage
            {
                Id = 17,
                ImageUrl = "HistoricalImages/21.jpg",
                HistoricalId = 5
            },
            new HistoricalImage
            {
                Id = 18,
                ImageUrl = "HistoricalImages/23.jpg",
                HistoricalId = 5
            },
            new HistoricalImage
            {
                Id = 19,
                ImageUrl = "HistoricalImages/24.jpg",
                HistoricalId = 5
            },
            new HistoricalImage
            {
                Id = 20,
                ImageUrl = "HistoricalImages/25.jpg",
                HistoricalId = 5
            },
            new HistoricalImage
            {
                Id = 21,
                ImageUrl = "HistoricalImages/27.jpg",
                HistoricalId = 6
            },
            new HistoricalImage
            {
                Id = 22,
                ImageUrl = "HistoricalImages/28.jpg",
                HistoricalId = 6
            },
            new HistoricalImage
            {
                Id = 23,
                ImageUrl = "HistoricalImages/29.jpg",
                HistoricalId = 6
            },
            new HistoricalImage
            {
                Id = 24,
                ImageUrl = "HistoricalImages/30.jpg",
                HistoricalId = 6
            },
            new HistoricalImage
            {
                Id = 25,
                ImageUrl = "HistoricalImages/32.jpeg",
                HistoricalId = 7
            },
            new HistoricalImage
            {
                Id = 26,
                ImageUrl = "HistoricalImages/33.jpg",
                HistoricalId = 7
            },
            new HistoricalImage
            {
                Id = 27,
                ImageUrl = "HistoricalImages/34.jpg",
                HistoricalId = 7
            },
            new HistoricalImage
            {
                Id = 28,
                ImageUrl = "HistoricalImages/35.jpg",
                HistoricalId = 7
            },
            new HistoricalImage
            {
                Id = 29,
                ImageUrl = "HistoricalImages/37.jpg",
                HistoricalId = 8
            },
            new HistoricalImage
            {
                Id = 30,
                ImageUrl = "HistoricalImages/38.jpg",
                HistoricalId = 8
            },
            new HistoricalImage
            {
                Id = 31,
                ImageUrl = "HistoricalImages/39.jpg",
                HistoricalId = 8
            },
            new HistoricalImage
            {
                Id = 32,
                ImageUrl = "HistoricalImages/40.jpg",
                HistoricalId = 8
            },
            new HistoricalImage
            {
                Id = 33,
                ImageUrl = "HistoricalImages/42.jpg",
                HistoricalId = 9
            },
            new HistoricalImage
            {
                Id = 34,
                ImageUrl = "HistoricalImages/43.jpg",
                HistoricalId = 9
            },
            new HistoricalImage
            {
                Id = 35,
                ImageUrl = "HistoricalImages/44.jpg",
                HistoricalId = 9
            },
            new HistoricalImage
            {
                Id = 36,
                ImageUrl = "HistoricalImages/45.jpg",
                HistoricalId = 9
            },
            new HistoricalImage
            {
                Id = 37,
                ImageUrl = "HistoricalImages/47.jpg",
                HistoricalId = 10
            },
            new HistoricalImage
            {
                Id = 38,
                ImageUrl = "HistoricalImages/48.jpg",
                HistoricalId = 10
            },
            new HistoricalImage
            {
                Id = 39,
                ImageUrl = "HistoricalImages/49.jpg",
                HistoricalId = 10
            },
            new HistoricalImage
            {
                Id = 40,
                ImageUrl = "HistoricalImages/50.jpg",
                HistoricalId = 10
            },
            new HistoricalImage
            {
                Id = 41,
                ImageUrl = "HistoricalImages/52.jpg",
                HistoricalId = 11
            },
            new HistoricalImage
            {
                Id = 42,
                ImageUrl = "HistoricalImages/53.jpg",
                HistoricalId = 11
            },
            new HistoricalImage
            {
                Id = 43,
                ImageUrl = "HistoricalImages/54.jpg",
                HistoricalId = 11
            },
            new HistoricalImage
            {
                Id = 44,
                ImageUrl = "HistoricalImages/55.jpg",
                HistoricalId = 11
            },
            new HistoricalImage
            {
                Id = 45,
                ImageUrl = "HistoricalImages/57.jpg",
                HistoricalId = 12
            },
            new HistoricalImage
            {
                Id = 46,
                ImageUrl = "HistoricalImages/58.jpg",
                HistoricalId = 12
            },
            new HistoricalImage
            {
                Id = 47,
                ImageUrl = "HistoricalImages/59.jpg",
                HistoricalId = 12
            },
            new HistoricalImage
            {
                Id = 48,
                ImageUrl = "HistoricalImages/60.webp",
                HistoricalId = 12
            },
            new HistoricalImage
            {
                Id = 49,
                ImageUrl = "HistoricalImages/61.jpg",
                HistoricalId = 13
            },
            new HistoricalImage
            {
                Id = 50,
                ImageUrl = "HistoricalImages/62.jpg",
                HistoricalId = 13
            },
            new HistoricalImage
            {
                Id = 51,
                ImageUrl = "HistoricalImages/64.jpg",
                HistoricalId = 13
            },
            new HistoricalImage
            {
                Id = 52,
                ImageUrl = "HistoricalImages/65.jpg",
                HistoricalId = 13
            },
            new HistoricalImage
            {
                Id = 53,
                ImageUrl = "HistoricalImages/66.jpg",
                HistoricalId = 14
            },
            new HistoricalImage
            {
                Id = 54,
                ImageUrl = "HistoricalImages/67.jpg",
                HistoricalId = 14
            },
            new HistoricalImage
            {
                Id = 55,
                ImageUrl = "HistoricalImages/68.jpg",
                HistoricalId = 14
            },
            new HistoricalImage
            {
                Id = 56,
                ImageUrl = "HistoricalImages/70.jpg",
                HistoricalId = 14
            },
            new HistoricalImage
            {
                Id = 57,
                ImageUrl = "HistoricalImages/72.jpg",
                HistoricalId = 15
            },
            new HistoricalImage
            {
                Id = 58,
                ImageUrl = "HistoricalImages/73.jpeg",
                HistoricalId = 15
            },
            new HistoricalImage
            {
                Id = 59,
                ImageUrl = "HistoricalImages/74.jpg",
                HistoricalId = 15
            },
            new HistoricalImage
            {
                Id = 60,
                ImageUrl = "HistoricalImages/75.jpg",
                HistoricalId = 15
            },
        };
        builder.HasData(historicalImage);

    }
}
