// <auto-generated />
using System;
using Egyptos.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Egyptos.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250316003712_AddTourGuideData")]
    partial class AddTourGuideData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Egyptos.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaTypeId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.AreaImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("AreaImages");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.AreaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AreaTypes");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.AreaWorking", b =>
                {
                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("WorkingId")
                        .HasColumnType("int");

                    b.HasKey("AreaId", "WorkingId");

                    b.HasIndex("WorkingId");

                    b.ToTable("AreaWorkings");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.BookingEventDate", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EventDateId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "EventDateId");

                    b.HasIndex("EventDateId");

                    b.ToTable("BookingEventDates");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.BookingHotel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("UserId", "HotelId");

                    b.HasIndex("HotelId");

                    b.ToTable("BookingHotels");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.BookingPrivateTransport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelBooking")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentCancel")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrivateTransportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PrivateTransportId");

                    b.HasIndex("UserId");

                    b.ToTable("BookingPrivateTransports");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.BookingTourGuide", b =>
                {
                    b.Property<int>("TourGuideId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndBooking")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartBooking")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("TourGuideId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("BookingTourGuides");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.BookingTrip", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "TripId");

                    b.HasIndex("TripId");

                    b.ToTable("BookingTrips");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.EventDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndSubscription")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActiveToSubscribe")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartSubscription")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventDates");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.EventImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventImages");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Historical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Historicals");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.HistoricalImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HistoricalId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HistoricalId");

                    b.ToTable("HistoricalImages");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerHour")
                        .HasColumnType("float");

                    b.Property<string>("WebSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e4b2f91d-9e12-4f4a-b3db-1b58fca15e66",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5c8298a9-982f-4d9d-a632-55f7d148f735",
                            Email = "admin@egyptos.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            ImageUrl = "profiles/Default-Image.jpg",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NationalId = "12345678901234",
                            NormalizedEmail = "ADMIN@EGYPTOS.COM",
                            NormalizedUserName = "ADMIN@EGYPTOS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6f3a18b3-c453-4a3a-b2e3-57f2e0429f50",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "admin@egyptos.com"
                        },
                        new
                        {
                            Id = "683211b1-1125-42a1-b148-a606a4ca4df3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b3c8f4ef-c9ab-49b5-9b16-06f17aa7668a",
                            Email = "Ahmed12@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ahmed",
                            ImageUrl = "profiles/df4fb389-64ed-486e-be7d-722771b6e3bc.jpeg",
                            LastName = "Hesham",
                            LockoutEnabled = false,
                            NationalId = "30305521354688",
                            NormalizedEmail = "AHMED12@GMAIL.COM",
                            NormalizedUserName = "AHMED12@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01024866094",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "46e17415-53e4-4e26-8ce4-3b9f91a4ebcd",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Ahmed12@gmail.com"
                        },
                        new
                        {
                            Id = "df2ea217-2e82-48b9-9442-47556c1a9403",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e09e586-695e-44ad-86a9-f7b49ba3552b",
                            Email = "Ali@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ali",
                            ImageUrl = "profiles/Outdoor Portraits — San Francisco Bay Area's Premier Personal Brand and Headshot Photographer _ Alpa.jpeg",
                            LastName = "Salama",
                            LockoutEnabled = false,
                            NationalId = "30308795612367",
                            NormalizedEmail = "ALI@GMAIL.COM",
                            NormalizedUserName = "ALI@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01134409876",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "287317a5-2b4e-4193-ade4-9b03c843b021",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Ali@gmail.com"
                        },
                        new
                        {
                            Id = "6b9b3e85-ce32-4944-9a46-601bb2b40000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a61c81ae-cdb2-4c92-ae17-75247a4cb5cb",
                            Email = "Hassan44@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Hassan",
                            ImageUrl = "profiles/Friendly Professional Business Headshot.jpeg",
                            LastName = "Alaa",
                            LockoutEnabled = false,
                            NationalId = "30306729061246",
                            NormalizedEmail = "HASSAN4412@GMAIL.COM",
                            NormalizedUserName = "HASSAN4412@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01079945073",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "33fe0c4e-09d7-4b8b-a625-7cf0651fb90e",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Hassan44@gmail.com"
                        },
                        new
                        {
                            Id = "fc4df06f-05c2-4751-96c1-8040f2761b7f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "30d973bd-092f-4869-ac70-0b1004519b48",
                            Email = "Mohamed@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mohamed",
                            ImageUrl = "profiles/82ebaf90-31fe-40ef-8358-99823ce3881d.jpeg",
                            LastName = "Mady",
                            LockoutEnabled = false,
                            NationalId = "30309871265308",
                            NormalizedEmail = "MOHAMED@GMAIL.COM",
                            NormalizedUserName = "MOHAMED@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01084670325",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4a5413d0-0b02-48f8-a24f-16b929d0af74",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Mohamed@gmail.com"
                        },
                        new
                        {
                            Id = "7c30ae16-67eb-4ff2-858f-70aa79aaa3c4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0a0bc059-4d5d-45dc-98dc-5e557d7aa1c1",
                            Email = "Maher@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Maher",
                            ImageUrl = "profiles/Rajan Velu.jpeg",
                            LastName = "Mohamed",
                            LockoutEnabled = false,
                            NationalId = "30301937508274",
                            NormalizedEmail = "MAHER@GMAIL.COM",
                            NormalizedUserName = "MAHER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01208173649",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "04a9f78c-43b0-4a6f-bb40-c161adb30b23",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Maher@gmail.com"
                        },
                        new
                        {
                            Id = "ce47a5ab-df14-416a-b500-9b544fa666a4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5d48db4f-16d7-418b-b97f-dbfe8616af56",
                            Email = "Nader@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Nader",
                            ImageUrl = "profiles/Mari Juliano.jpeg",
                            LastName = "Ahmed",
                            LockoutEnabled = false,
                            NationalId = "303020837616543",
                            NormalizedEmail = "NADER@GMAIL.COM",
                            NormalizedUserName = "NADER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01147893547",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e68c1657-3cb1-4097-a45f-27c1a655c81f",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Nader@gmail.com"
                        },
                        new
                        {
                            Id = "249aa6c5-d578-4517-8a42-48f24a7d959e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e7ed49bc-72fb-42be-afc5-fbd0351bd759",
                            Email = "Khaled@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Khaled",
                            ImageUrl = "profiles/MEN - Location - Headshot Photography by Brandon Tabiolo.jpeg",
                            LastName = "Mostafa",
                            LockoutEnabled = false,
                            NationalId = "30301920482846",
                            NormalizedEmail = "KHALED@GMAIL.COM",
                            NormalizedUserName = "KHALED@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01293749183",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f85433e6-bf5b-4ffc-9d02-3a7cc9938547",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Khaled@gmail.com"
                        },
                        new
                        {
                            Id = "49a438ba-672d-41d5-97ba-5536ffbec2a6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f9773109-8364-4c61-a5d4-9fe85a58c0f4",
                            Email = "Kareem@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Kareem",
                            ImageUrl = "profiles/Why I Mainly Photograph in Portrait Orientation for Actors' Headshots.jpeg",
                            LastName = "Maged",
                            LockoutEnabled = false,
                            NationalId = "303092689146845",
                            NormalizedEmail = "KAREEM@GMAIL.COM",
                            NormalizedUserName = "KAREEM@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01024860821",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aed0822d-8180-49b3-85cc-a4f5a33a3b56",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Kareem@gmail.com"
                        },
                        new
                        {
                            Id = "bf2ee728-59af-45ec-9b70-e5f5e27eef8e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "43d7bf34-bc3a-4d7f-841e-f1dfd028303d",
                            Email = "Halem@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Halem",
                            ImageUrl = "profiles/Gorgeous smile of Alexis Petit.jpeg",
                            LastName = "Ebrahim",
                            LockoutEnabled = false,
                            NationalId = "30308391092836",
                            NormalizedEmail = "HALEM@GMAIL.COM",
                            NormalizedUserName = "HALEM@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01049182640",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "999faa1d-9041-4c56-888c-42b8286d68b7",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Halem@gmail.com"
                        },
                        new
                        {
                            Id = "cb3cb7ca-1921-49fd-a11e-600b351b3df2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c76ae4f3-37a2-4707-b71b-f5d99f6f50da",
                            Email = "Salma@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Salma",
                            ImageUrl = "profiles/Women in Business.jpeg",
                            LastName = "Mostafa",
                            LockoutEnabled = false,
                            NationalId = "30302901738376",
                            NormalizedEmail = "SALMA@GMAIL.COM",
                            NormalizedUserName = "SALMA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01029836539",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2121aa48-49d8-4b1e-841e-48a7e61b0863",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Salma@gmail.com"
                        },
                        new
                        {
                            Id = "cb3cb7ca-1921-49fd-a11e-600b351b3df3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f58fbbd5-a0d4-460c-bc0d-5afb9a0adb63",
                            Email = "Jesseyd@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Jessy",
                            ImageUrl = "profiles/9151a7a4-4fc2-4bb0-a427-f97f4127e661.jpeg",
                            LastName = "Danial",
                            LockoutEnabled = false,
                            NationalId = "40415678901625",
                            NormalizedEmail = "JESSEYD@GMAIL.COM",
                            NormalizedUserName = "JESSEYD@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "07022670816",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4dd9dcd-8ef8-40fa-b1ac-6a6caa133079",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Jesseyd@gmail.com"
                        },
                        new
                        {
                            Id = "5d577849-97d1-4984-bf96-6fee7d08c8be",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "edb44c87-00c3-488a-9b74-2fc632b48bfc",
                            Email = "Marry@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mary",
                            ImageUrl = "profiles/468f9794-778b-429f-bea8-b7440810819d.jpeg",
                            LastName = "John",
                            LockoutEnabled = false,
                            NationalId = "40423109753269",
                            NormalizedEmail = "MARRY@GMAIL.COM",
                            NormalizedUserName = "MARRY@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "02029837399",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e27dc6f7-4bf0-44a1-a3fb-8b3e5239e87f",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Marry@gmail.com"
                        },
                        new
                        {
                            Id = "f89bca4a-8fc9-4259-a46d-22562907c27f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c615d822-a4fc-4a3a-8b23-b4b6c155b96a",
                            Email = "Mark@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            ImageUrl = "profiles/44050f40-662d-408b-9dda-9e3271d7c36e.jpeg",
                            LastName = "ALbrto",
                            LockoutEnabled = false,
                            NationalId = "4042098715635491",
                            NormalizedEmail = "MARK@GMAIL.COM",
                            NormalizedUserName = "MARK@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "070901468297",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6909260d-6430-4133-868e-9091e01fe56f",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Mark@gmail.com"
                        },
                        new
                        {
                            Id = "cb3cb7ca-1921-49fd-a11e-600b351b3df4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f58fbbd5-a0d4-460c-bc0d-5afb9a0adb63",
                            Email = "Jessey@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Jessy",
                            ImageUrl = "profiles/9151a7a4-4fc2-4bb0-a427-f97f4127e661.jpeg",
                            LastName = "MArk",
                            LockoutEnabled = false,
                            NationalId = "40415678901625",
                            NormalizedEmail = "JESSEY@GMAIL.COM",
                            NormalizedUserName = "JESSEY@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "07022670816",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4dd9dcd-8ef8-40fa-b1ac-6a6caa133079",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Jessey@gmail.com"
                        },
                        new
                        {
                            Id = "8766c317-1eaa-468a-b34d-59790c8eb915",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c4986d9a-0ff6-4ecb-9f51-b8bb5dc826e4",
                            Email = "Rana@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Rana",
                            ImageUrl = "profiles/2edc3141-b4cd-411d-9136-33440bbb1c03.jpeg",
                            LastName = "Osama",
                            LockoutEnabled = false,
                            NationalId = "30304597102873",
                            NormalizedEmail = "RANA@GMAIL.COM",
                            NormalizedUserName = "RANA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01028649032",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f5e74c9d-fe75-442e-a90e-6400f6a2f0c7",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Rana@gmail.com"
                        },
                        new
                        {
                            Id = "10eb7637-95f4-45d2-b200-84dbb188ec41",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1ca42846-c687-48a2-9eb4-77fc5f21ae44",
                            Email = "Ramy@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ramy",
                            ImageUrl = "profiles/16 Black Chefs Changing Food in America (Published 2019).jpeg",
                            LastName = "Aziz",
                            LockoutEnabled = false,
                            NationalId = "30303409168364",
                            NormalizedEmail = "RAMY@GMAIL.COM",
                            NormalizedUserName = "RAMY@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "011298640281",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f439954d-63d4-4e36-8a5f-827f533cc6a1",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Ramy@gmail.com"
                        },
                        new
                        {
                            Id = "357c8ce0-ed6e-4979-b1f9-5e0f6e90c9a1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d607b523-2920-4ea8-83c4-2103dbb45b0a",
                            Email = "Rola@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Rola",
                            ImageUrl = "profiles/Before and After_ Transforming Your LinkedIn Profile with AI Headshots.jpeg",
                            LastName = "Samy",
                            LockoutEnabled = false,
                            NationalId = "30306183028747",
                            NormalizedEmail = "ROLA@GMAIL.COM",
                            NormalizedUserName = "ROLA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "012938475601",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eac93f1e-749b-4c66-9783-c46c16b4ffbf",
                            Sex = "Female",
                            TwoFactorEnabled = false,
                            UserName = "Rola@gmail.com"
                        },
                        new
                        {
                            Id = "a0e2f1e7-53e5-416f-b0b0-ca4668563233",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a46ec364-f74a-455e-93f2-471913135d05",
                            Email = "Malek@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Malek",
                            ImageUrl = "profiles/9c12d50d-5cbe-4c75-8bca-cbc57d504a7b.jpeg",
                            LastName = "Mohamed",
                            LockoutEnabled = false,
                            NationalId = "30308103829384",
                            NormalizedEmail = "MALEK@GMAIL.COM",
                            NormalizedUserName = "MALEK@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01283604718",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "16dd3214-5abc-48b6-83cd-df00d21f16dc",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Malek@gmail.com"
                        },
                        new
                        {
                            Id = "52511e3a-0690-45b0-9e52-02667a473b18",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e184b3aa-6771-4830-83f9-b1a59c9676c4",
                            Email = "Magdy@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Magdy",
                            ImageUrl = "profiles/Dallas Headshots Photographer - Willie & Kim Photography.jpeg",
                            LastName = "Abdallah",
                            LockoutEnabled = false,
                            NationalId = "30301789256730",
                            NormalizedEmail = "MAGDY@GMAIL.COM",
                            NormalizedUserName = "MAGDY@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN6vZ01506YX1ctq2EthavTlwjZTRO5AjuoQ5LDjMQ+cpfTdIRy0cPAFQfqq4zbWYA==",
                            PhoneNumber = "01183670178",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fda38b97-da47-40ba-bbe3-702a78f4e009",
                            Sex = "Male",
                            TwoFactorEnabled = false,
                            UserName = "Magdy@gmail.com"
                        });
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.PrivateTransport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerHour")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TransportTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransportTypeId");

                    b.ToTable("PrivateTransports");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.PublicTransport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsAvailable")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("PublicTransports");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.TourGuide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<double>("SalaryPerHour")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TourGuides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A passionate tour guide with in-depth knowledge of historical landmarks and cultural heritage, dedicated to providing engaging and educational experiences.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 150.0,
                            UserId = "683211b1-1125-42a1-b148-a606a4ca4df3",
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Experienced tour guide specializing in archaeological sites, offering insightful narratives that bring history to life.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 150.0,
                            UserId = "df2ea217-2e82-48b9-9442-47556c1a9403",
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Friendly and knowledgeable guide, ensuring every visitor enjoys a personalized and immersive travel experience.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 150.0,
                            UserId = "6b9b3e85-ce32-4944-9a46-601bb2b40000",
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Expert in local history and traditions, delivering memorable tours that blend education and entertainment.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 150.0,
                            UserId = "fc4df06f-05c2-4751-96c1-8040f2761b7f",
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "A dynamic storyteller who transforms every tour into a fascinating journey through time and culture.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 150.0,
                            UserId = "7c30ae16-67eb-4ff2-858f-70aa79aaa3c4",
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Fluent in multiple languages, offering exceptional guided experiences for travelers from around the world.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 300.0,
                            UserId = "ce47a5ab-df14-416a-b500-9b544fa666a4",
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Skilled in adventure tourism, leading exciting and informative tours through natural wonders and historical landmarks.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 300.0,
                            UserId = "249aa6c5-d578-4517-8a42-48f24a7d959e",
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Passionate about sharing hidden gems and off-the-beaten-path locations with travelers seeking authentic experiences.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 300.0,
                            UserId = "49a438ba-672d-41d5-97ba-5536ffbec2a6",
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "A certified tour guide with years of experience, ensuring visitors gain deep insights into historical and modern attractions.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 300.0,
                            UserId = "bf2ee728-59af-45ec-9b70-e5f5e27eef8e",
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "Dedicated to providing an unforgettable journey through historical sites, blending education with entertainment.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 300.0,
                            UserId = "cb3cb7ca-1921-49fd-a11e-600b351b3df2",
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "An enthusiastic guide who loves connecting people with the rich history and traditions of the region.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 500.0,
                            UserId = "cb3cb7ca-1921-49fd-a11e-600b351b3df3",
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 12,
                            Description = "Expert in eco-tourism, offering sustainable and immersive travel experiences for nature lovers.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 500.0,
                            UserId = "5d577849-97d1-4984-bf96-6fee7d08c8be",
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 13,
                            Description = "Combining storytelling with historical facts to create engaging and interactive guided tours.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 500.0,
                            UserId = "f89bca4a-8fc9-4259-a46d-22562907c27f",
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 14,
                            Description = "A charismatic and knowledgeable guide, ensuring tourists leave with a deeper appreciation for the destination.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 500.0,
                            UserId = "cb3cb7ca-1921-49fd-a11e-600b351b3df4",
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "Certified heritage interpreter, offering in-depth explorations of ancient and modern cultural landmarks.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 500.0,
                            UserId = "8766c317-1eaa-468a-b34d-59790c8eb915",
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 16,
                            Description = "Well-versed in local customs, history, and cuisine, providing a holistic travel experience for every visitor.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 4000.0,
                            UserId = "52511e3a-0690-45b0-9e52-02667a473b18",
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 17,
                            Description = "Professional and friendly guide who creates customized tours to meet the interests of each group.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 750.0,
                            UserId = "a0e2f1e7-53e5-416f-b0b0-ca4668563233",
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 18,
                            Description = "A history enthusiast dedicated to making every tour an unforgettable and enriching experience.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 700.0,
                            UserId = "357c8ce0-ed6e-4979-b1f9-5e0f6e90c9a1",
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 19,
                            Description = "Providing top-tier guided tours that blend adventure, history, and culture for an unforgettable experience.",
                            IsActive = true,
                            IsAvailable = true,
                            Rate = 3.0,
                            SalaryPerHour = 750.0,
                            UserId = "10eb7637-95f4-45d2-b200-84dbb188ec41",
                            YearsOfExperience = 5
                        });
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.TourGuideTrip", b =>
                {
                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("TourGuideId")
                        .HasColumnType("int");

                    b.HasKey("TripId", "TourGuideId");

                    b.HasIndex("TourGuideId");

                    b.ToTable("TourGuideTrips");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.TransportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransportTypes");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("BackTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("PublicTransportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("PublicTransportId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Working", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Workings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0191d311-2918-7f76-bd8a-0bded8535075",
                            ConcurrencyStamp = "0191d311-2918-7f76-bd8a-0be08dd83078",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "ce2fd704-7a3c-4a03-846e-c5479a8b921d",
                            ConcurrencyStamp = "aacecacd-28e1-43cc-92da-decb1f9b32c4",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = "6CCF2454-C7FE-4F58-89FB-F565AE5643E3",
                            ConcurrencyStamp = "B1F115C4-D298-4C6D-AA7B-6C7DC785A1C5",
                            Name = "TourGuide",
                            NormalizedName = "TOURGUIDE"
                        },
                        new
                        {
                            Id = "0191d311-2918-7f76-bd8a-0bdf740adff8",
                            ConcurrencyStamp = "0191d311-2918-7f76-bd8a-0be100f11384",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Area", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.AreaType", "AreaType")
                        .WithMany("Areas")
                        .HasForeignKey("AreaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaType");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.AreaImage", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.Area", "Area")
                        .WithMany("AreaImages")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.AreaWorking", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.Area", "Area")
                        .WithMany("AreaWorkings")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egyptos.Domain.Entities.Working", "Working")
                        .WithMany("AreaWorkings")
                        .HasForeignKey("WorkingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Working");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.BookingEventDate", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.EventDate", "EventDate")
                        .WithMany()
                        .HasForeignKey("EventDateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egyptos.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("BookingEventDates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventDate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.BookingHotel", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.Hotel", "Hotel")
                        .WithMany("BookingHotels")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egyptos.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("BookingHotels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.BookingPrivateTransport", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.PrivateTransport", "PrivateTransport")
                        .WithMany("BookingPrivateTransports")
                        .HasForeignKey("PrivateTransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egyptos.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("BookingPrivateTransports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivateTransport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.BookingTourGuide", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.TourGuide", "TourGuide")
                        .WithMany("BookingTourGuides")
                        .HasForeignKey("TourGuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egyptos.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("BookingTourGuides")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourGuide");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.BookingTrip", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.Trip", "Trip")
                        .WithMany("BookingTrips")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egyptos.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("BookingTrips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Event", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.EventDate", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.Event", "Event")
                        .WithMany("EventDates")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.EventImage", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.EventDate", "Event")
                        .WithMany("EventImages")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.HistoricalImage", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.Historical", "Historical")
                        .WithMany("HistoricalImages")
                        .HasForeignKey("HistoricalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Historical");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Item", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.Area", null)
                        .WithMany("Items")
                        .HasForeignKey("AreaId");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.PrivateTransport", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.TransportType", "TransportType")
                        .WithMany("PrivateTransports")
                        .HasForeignKey("TransportTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportType");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Report", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.TourGuide", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.TourGuideTrip", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.TourGuide", "TourGuide")
                        .WithMany("TourGuideTrips")
                        .HasForeignKey("TourGuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egyptos.Domain.Entities.Trip", "Trip")
                        .WithMany("TourGuideTrips")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourGuide");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Trip", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.Area", "Area")
                        .WithMany("Trips")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egyptos.Domain.Entities.PublicTransport", "PublicTransport")
                        .WithMany()
                        .HasForeignKey("PublicTransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("PublicTransport");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egyptos.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Egyptos.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Area", b =>
                {
                    b.Navigation("AreaImages");

                    b.Navigation("AreaWorkings");

                    b.Navigation("Items");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.AreaType", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Event", b =>
                {
                    b.Navigation("EventDates");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.EventDate", b =>
                {
                    b.Navigation("EventImages");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Historical", b =>
                {
                    b.Navigation("HistoricalImages");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Hotel", b =>
                {
                    b.Navigation("BookingHotels");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("BookingEventDates");

                    b.Navigation("BookingHotels");

                    b.Navigation("BookingPrivateTransports");

                    b.Navigation("BookingTourGuides");

                    b.Navigation("BookingTrips");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.PrivateTransport", b =>
                {
                    b.Navigation("BookingPrivateTransports");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.TourGuide", b =>
                {
                    b.Navigation("BookingTourGuides");

                    b.Navigation("TourGuideTrips");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.TransportType", b =>
                {
                    b.Navigation("PrivateTransports");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Trip", b =>
                {
                    b.Navigation("BookingTrips");

                    b.Navigation("TourGuideTrips");
                });

            modelBuilder.Entity("Egyptos.Domain.Entities.Working", b =>
                {
                    b.Navigation("AreaWorkings");
                });
#pragma warning restore 612, 618
        }
    }
}
